name: Deploy site to Pages

on:
  push:
    branches:
      - main
  discussion:
    types: [created, edited, deleted]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Noll
        uses: actions/checkout@v4
        with:
          repository: NollGo/Noll
          ref: d19d54c
          path: "./Noll"

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version-file: './Noll/go.mod'

      - name: Build Noll
        run: |
          cd ./Noll
          go mod tidy
          go build --ldflags="-w -s"
          chmod 775 ./io.github.nollgo

      - name: Build site
        run: |
          repository=${{ github.repository }}
          repositoryName=$(basename "$repository")
          pagesPath="./"
          baseURL="/$repositoryName"
          gamID="${{ vars.GAMID }}"
          echo "ARGS: ${{ github.repository_owner }}, $repositoryName, ${{secrets.GITHUB_TOKEN}}, $pagesPath, $baseURL, $gamID,"
          if [ -z "$gamID" ]; then
            ./Noll/io.github.nollgo -owner ${{ github.repository_owner }} -name $repositoryName  -token ${{secrets.GITHUB_TOKEN}} -pages "$pagesPath" -baseURL "$baseURL"
          else
          ./Noll/io.github.nollgo -owner ${{ github.repository_owner }} -name $repositoryName  -token ${{secrets.GITHUB_TOKEN}} -pages "$pagesPath" -baseURL "$baseURL" -gamID "$gamID"
          fi
          ls -a -lh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: "./"

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
